### ISSUE TITLE
[Bug] logo images

### ISSUE THREAD

**Issue by strauhmanis** [daviddarnes/alembic#109]
It would appear that only logo images with some specific properties may work as a replacement for the default logo, as no matter what I tried to throw in as replacement for the default logo, it never worked—just a blank space.

Attached are 3 images created in Adobe Illustrator with different SVG export properties.

[SVG logos.zip](https://github.com/daviddarnes/alembic/files/2400157/SVG.logos.zip)

**Comment by daviddarnes** [comment]
That is strange, which ones from the zip worked @strauhmanis? Interesting that you're using Illustrator, I've been using Sketch to export SVGs. Maybe the difference lies there?

**Comment by strauhmanis** [comment]
None of the 3 attached images created in Adobe Illustrator worked. And neither did images produced by Affinity Designer.

Images created in Sketch did work! And that turned out to be because Sketch added `width` and `height` attributes.

When I added these attributes to images created in Illustrator / Designer, they started to be displayed as logo replacement.

A simple edit that involved changing `max-height` to `height` for logo settings in `_theme.scss` made both kinds of SVG images, those that did or did not have `width` and `height` attributes, to act as logo images.

**Comment by daviddarnes** [comment]
@strauhmanis ah I see. That may be intensional, adding a width and height to images and SVGs reduce the amount of computation time on in the browser. Essentially letting the browser know the dimensions before the graphic/ image has loaded. However it does seem irritating that the images don't appear anyway. A default size range in CSS is probably the best work around
