### ISSUE TITLE
[Proposal] Extending Javascript snippets

### ISSUE THREAD

**Issue by boynux** [daviddarnes/alembic#111]
I'd like to extend my blog and add user consent popup using JS. However I could not find any options to do that. I'm using `remote_theme` plugin.

it'd be cool if I could do something like this:

```
include_header_js:
  - path-to-js-file
```

**Comment by daviddarnes** [comment]
@boynux cool idea! I have thought about having hooks so extra code can be inserted. However if you're struggling to add in the code yourself you could always replace the default layout with your own and copy the current code in? Just offering an alternative solution

**Comment by boynux** [comment]
@daviddarnes thanks for the suggestion, that's what I ended up doing, however since I'm using remote themes, this prevents to get upsteam changes easily.
If you think it's good feature to have, I can work on a PR, wdyt?

**Comment by daviddarnes** [comment]
@boynux yea you're right, having a specific way to inserting extra code would be beneficial. It would need to be robust and simple though, this is the type of feature that sits on the fence of theme and framework that makes sense 😅

**Comment by boynux** [comment]
@daviddarnes created a PR, please have a look and let me know if can be improved.
