### ISSUE TITLE
**[Proposal]** Support IP Anonymization for Google Analytics

### ISSUE THREAD

**Issue by freyley** [daviddarnes/alembic#117]
Given GDPR, IP Anonymization seems like a good practice for many users of Google Analytics. There appear to be a few different ways to configure this, but one way that I've found would be to change, in `_includes/site_analytics.html`

`gtag('config', '{{ site.google_analytics }}');`

to

`gtag('config', '{{ site.google_analytics }}', { 'anonymize_ip': true });`

Which could be

`gtag('config', '{{ site.google_analytics }}', { 'anonymize_ip': {{site.google_analytics_ip_anonymization }} });`

I would make a PR for this, but I haven't found out how to make the default for site.google_analytics_ip_anonymization be `false` if it isn't set.

**Comment by daviddarnes** [comment]
Hey @freyley! This seems like a great idea and considerate to anyone viewing a site using Alembic. Returning `false` by default can be done with
`{{ site.google_analytics_anonymize_ip | default: "false" }}`.

Would be great if you can make a PR for this 👍
