### ISSUE TITLE
**[Question]** Shouldn't "theme: alembic-jekyll-theme" be in _config.yml?

### ISSUE THREAD

**Issue by kristiannordestgaard** [daviddarnes/alembic#121]
Hello,

I was wondering if maybe `theme: alembic-jekyll-theme` was omitted from `_config.yml` by mistake?

**Comment by daviddarnes** [comment]
Hey, that’s a fair question. It’s omitted because this repo _is_ the theme and doesn’t need to reference the theme to get all the code for it. If you look at this repo you’ll see the theme key has been set how you expect https://github.com/daviddarnes/alembic-kit
