### ISSUE TITLE
**[Bug]** When rotating some mobile devices, the menu disappears 

### ISSUE THREAD

**Issue by kristiannordestgaard** [daviddarnes/alembic#123]
The menu disappears until you click the site icon after rotating some devices. 

**Steps to reproduce**
1. Go to https://alembic.darn.es/ in your Chrome browser
2. Go to inspect mode, set Galaxy S5 as the device
3. Go to horizontal mode, and click the menu if it is not minimized (burger mode)
4. Rotate the virtual screen, and the menu is now gone until you click the site logo to the left

I reproduced this on my phone as well.

**Comment by kristiannordestgaard** [comment]
Someone on IRC told me that this code is the problem: 

`@media screen and (min-width: 40em){.button--nav{display:none}}`

Please note that this is the rendered CSS.

**Comment by daviddarnes** [comment]
Hey @kristiannordestgaard, thanks for spotting this. I've been aware of the bug but not spent the time to delve into it as it's somewhat an edge case. I'll look into it now though if you are experiencing the issue. I think it's just down to the javascript not being re-initialised when the browser resizes, aka when rotating the device

**Comment by kristiannordestgaard** [comment]
I tried the with the new version of `nav-header.html`, but now the menu won't expand while in horizontal mode.

**Comment by daviddarnes** [comment]
@kristiannordestgaard do you have a screenshot or gif of this? I've just tested the screen size of a Galaxy S5 and the whole nav shows, see below
<img width="663" alt="Screenshot 2019-03-31 at 16 23 32" src="https://user-images.githubusercontent.com/1177460/55290948-79e79080-53d1-11e9-9183-6751ab75b48e.png">

**Comment by kristiannordestgaard** [comment]
Yes, here is a screenshot. I see that I wrote something wrong, because the problem is there in *vertical* mode, with the burger menu. This is what happens when I try to expand it: 

![alembic](https://user-images.githubusercontent.com/2007931/55291131-6d683580-53db-11e9-9bb0-773b71e0bb27.png)

**Comment by daviddarnes** [comment]
@kristiannordestgaard I've tried a newer version if you want to try it. It's using CSS custom properties but if the browser doesn't support it then the nav will show by default. Seems to be working better now

**Comment by kristiannordestgaard** [comment]
@daviddarnes Works here too! Thank you so much!
