### ISSUE TITLE
Syntax highlighting with Rouge doesnt work as intended

### ISSUE THREAD

**Issue by vgoel** [daviddarnes/alembic#126]
I have configured Rouge for my site for syntax highlighting.

Rouge seems to work fine with the colours showing up but the only issue is that it is always on a white background in Alembic despite choosing a dark theme (for example monokai). Is there something I am missing from a configuration perspective?

**Comment by daviddarnes** [comment]
Hey @vgoel, looks like this is set using the `$captionColour` variable in the `sass/_settings.scss` file. This colour is used by the main theme code as well as Sassline which is the typography framework used in Alembic. Sorry it's so fiddly to change, but the best way is to set a colour in your own styles. Something like this:
``` css
.typeset pre {
  background: #333;
}
```
This will overwrite what is being set in the theme. Hope this helps.

_PS. I would like to strip out Sassline sometime in the future, but at the minute it's doing more good that bad in the theme_
