### ISSUE TITLE
[Proposal] Add `!default" to allow sass color overwrites 

### ISSUE THREAD

**Issue by jonashoechst** [daviddarnes/alembic#127]
Adding a `!default` tag to the defined variables allows the users to overwrite the variables in a file importing the theme.

This is especially useful when using the theme as a GitHub pages remote theme.

The change was also discussed and implemented for the cayman theme: https://github.com/pages-themes/cayman/pull/11

Thank you for considering!

**Comment by daviddarnes** [comment]
I didn't know this was caused them to work like that! Will definitely add this in when I get a chance, thanks @jonashoechst

**Comment by jonashoechst** [comment]
Thanks for the enchantment. However you seem to have missed `$accentColour`, is this by accident?

**Comment by daviddarnes** [comment]
@jonashoechst urgh sorry, this was by accident. Hopefully get to it soon, however feel free to make a pull request to fix it! 😃
