### ISSUE TITLE
[Bug] bundle install with `github-pages = 198` results in an unresolveable dependency tree

### ISSUE THREAD

**Issue by komidore64** [daviddarnes/alembic#128]
**Please read the [contributing guidelines](https://github.com/daviddarnes/alembic/blob/master/.github/CONTRIBUTING.md) and [code of conduct](https://github.com/daviddarnes/alembic/blob/master/.github/CODE_OF_CONDUCT.md) before creating an issue.**

Please prefix your issue with one of the following: **[Bug]** **[Proposal]** **[Question]**.

Please provide as much information as possible, ideally a summary to describe the issue and / or steps to reproduce the issue.

---

Creating a brand new project with the following Gemfile results in an unresolveable dependency tree on `bundle install`:

```ruby
source 'https://rubygems.org'

require 'json'
require 'open-uri'

ruby '~> 2.6.0'

gem 'github-pages', JSON.parse(open('https://pages.github.com/versions.json').read)['github-pages']
gem 'alembic-jekyll-theme'
```

As of 16 May 2019, `github-pages`'s latest version is `198`.

The following output is returned:

```
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    github-pages (= 198) was resolved to 198, which depends on
      activesupport (= 4.2.11.1)

    github-pages (= 198) was resolved to 198, which depends on
      jekyll-mentions (= 1.4.1) was resolved to 1.4.1, which depends on
        html-pipeline (~> 2.3) was resolved to 2.11.0, which depends on
          activesupport (>= 2)

Bundler could not find compatible versions for gem "jekyll-feed":
  In Gemfile:
    alembic-jekyll-theme was resolved to 1.5.3, which depends on
      jekyll-feed (~> 0.5)

    github-pages (= 198) was resolved to 198, which depends on
      jekyll-feed (= 0.11.0)

Bundler could not find compatible versions for gem "jekyll-mentions":
  In Gemfile:
    alembic-jekyll-theme was resolved to 1.5.3, which depends on
      jekyll-mentions (~> 1.2)

    github-pages (= 198) was resolved to 198, which depends on
      jekyll-mentions (= 1.4.1)

Bundler could not find compatible versions for gem "jekyll-sitemap":
  In Gemfile:
    alembic-jekyll-theme was resolved to 1.5.3, which depends on
      jekyll-sitemap (~> 0.10)

    github-pages (= 198) was resolved to 198, which depends on
      jekyll-sitemap (= 1.2.0)

Bundler could not find compatible versions for gem "jemoji":
  In Gemfile:
    alembic-jekyll-theme was resolved to 1.5.3, which depends on
      jemoji (~> 0.7)

    github-pages (= 198) was resolved to 198, which depends on
      jemoji (= 0.10.2)
```

**Comment by daviddarnes** [comment]
Yikes! Thanks for reporting this @komidore64. How did you discover it, from just trying to do a build or some kind of automated build?

**Comment by komidore64** [comment]
> How did you discover it, from just trying to do a build or some kind of automated build?

Simply started working on a new personal site and **whamo**!

**Comment by daviddarnes** [comment]
Sorry, but I just realised what you're trying to do. Custom theme gems aren't supported by GitHub Pages, so trying to install the gem along with the GitHub Pages gems won't be beneficial. If you're wanting to use GitHub Pages I'd recommend following [the remote theme installation steps in the readme](https://github.com/daviddarnes/alembic#as-a-github-pages-remote-theme)

However if you're wanting to install the gem theme in the typical fashion you'll need to skip installing the github-pages gem and it's dependencies. Just install [Jekyll and the theme itself](https://github.com/daviddarnes/alembic#as-a-jekyll-theme) and it will come with all the dependencies you require. Hope this helps!

**Comment by komidore64** [comment]
Ah I understand now. Thank you for the explanation. Looking at the theme docs, it read like I had choices as opposed to step 1 ("As a Jekyll theme") being incompatible with GitHub Pages.

Thanks again!
