### ISSUE TITLE
Navigation buttons are missing

### ISSUE THREAD

**Issue by onmyway133** [daviddarnes/alembic#134]
Hi, thanks for the wonderful theme, I like it a lot, I use it in my blog https://onmyway133.github.io/. It works perfectly until yesterday. Now the navigation buttons are missing but my yml file remains unchanged https://github.com/onmyway133/onmyway133.github.io/blob/master/_config.yml

How to remedy this? Thanks

**Comment by daviddarnes** [comment]
Thanks for the kind words @onmyway133! The reason for the issue is due to [some breaking changes in the theme](https://github.com/daviddarnes/alembic/releases/tag/3.1.0). I've made a [pull request to your blog to fix the navigation](https://github.com/onmyway133/onmyway133.github.io/pull/1)
