### ISSUE TITLE
[Bug] Theme + External Gems don't work on GH Pages

### ISSUE THREAD

**Issue by kkhan01** [daviddarnes/alembic#137]
**Issue:** I want to use gems other than the default theme gems. One of the important ones for me is [jekyll-org](https://github.com/eggcaker/jekyll-org), which allows posts to be [org files](https://orgmode.org/). I currently have just a little [test website](https://github.com/kkhan01/kkhan01.github.io/tree/264937f9e5de04b35e18978ad3ff4845663e497d). Although the content isn't important right now, it serves as an example which can be cloned and tested with. My issue is that when I use `bundle exec jekyll serve`, the site works fine and parses the org files as it should. But when I deploy to github pages, it seems the gems other than the theme gems are not being used.

**To Replicate:** Using the [GitHub Pages with remote theme kit](https://github.com/daviddarnes/alembic-kit/archive/remote-theme.zip) found on the [theme's main site](https://alembic.darn.es/), add in:
- `- jekyll-org` to `plugins:` in the `_config.yml` file
- `gem 'jekyll-org'` into the `Gemfile`

**Comment by kkhan01** [comment]
P.S.: I realize that this may actually be the gem's fault instead, but I'm not sure yet.

**Comment by kkhan01** [comment]
Mhm, I've believe this is due to github's exclusive use of "whitelisted" gems.

**Comment by daviddarnes** [comment]
You're totally correct, bit of a pain right? Have you tried Netlify? [netlify.com](netlify.com)

**Comment by kkhan01** [comment]
I'm currently trying it, but since it's my first time, I'm struggling a little bit with deploying the repo/ setting up the custom domain. Thanks though!
