### ISSUE TITLE
index page does not display header

### ISSUE THREAD

**Issue by mark-petersen** [daviddarnes/alembic#139]
**[Bug]**

David, thanks for your beautiful web design. I have an exact copy of your repo and set it as a github page here:
https://lillianpetersen.github.io/elements/
but the home page does not display the header, it only shows the content of index.md:
https://lillianpetersen.github.io/

Have you ever seen that before? It might be a github pages bug, rather than related to alembic. This started when I copied a few simple html pages into the top directory, but after I deleted them, and then even reverted to the head of your repo, it did not fix.

I'm on your last commit 174733d, but removed the CNAME file. But it happened the first time with an alteration of a 2017 commit, aaa56f0, so it is not any problem that was recently introduced.

**Comment by mark-petersen** [comment]
Well, I found a work-around. I copied `index.md` to `home.md` and put the line:
```
<meta http-equiv="Refresh" content="0; url=//lillianpetersen.github.io/home" />
```
at the top of `index.md`. The problem was mysterious, but probably not worth investigating.

**Comment by daviddarnes** [comment]
Hey @mark-petersen, I think that's a configuration bug at your end. Not sure why the nav wouldn't be appearing, it could be the formatting in your `index.md` or that you need to set the layout to 'page'
