### ISSUE TITLE
[Question] Customize CSS but not working

### ISSUE THREAD

**Issue by sammiehsieh** [daviddarnes/alembic#140]
Hi ✋ ,

I'm using Alembic as my GitHub page theme. Thank you for designing this great, beautiful theme, also clearly explain how to use it with many details.

Since I'm very new to Github page, gem and jekyll. I've read the configuration but still don't know how to change CSS style such as font-family.

I've downloaded the GitHub kit which you mentioned in `README.md`, after installing things in my repo, there's only one CSS file named styles.css (not styles.scss), so I've changed font-family in `_site/assets/styles.css`, then save and commit it, everything goes fine so far.

But after I run `$ bundle exec jekyll serve`, those changes I've done are all back to original setting, and the file also tag as modified in git.

I've tried to add `/assets/styles.css`, `/assets/*` or `styles.css` in `_config.yml` with exclude files, but it's not working either.

I'm not sure if I did anything wrong, or am I missing something? Do you have any suggestions or could you guide me how to do it?

Thank you for your help!

**Comment by daviddarnes** [comment]
I think you misread the docs, you should be creating a new SCSS file at `assets/styles.scss` and copy the [contents of this file into it](https://github.com/daviddarnes/alembic/blob/master/assets/styles.scss). From there you can apply your own CSS. Regular CSS can be written fine in an SCSS file, jekyll will handle the compiling for you.
More info on this in the docs: https://github.com/daviddarnes/alembic#customising

**Comment by sammiehsieh** [comment]
omg :sweat_smile: no wonder I couldn't change font-family no matter how I tried.
Thank you so much!!
