### ISSUE TITLE
[Bug] Build warning about invalid layouts

### ISSUE THREAD

**Issue by johannes-jansson** [daviddarnes/alembic#141]
This output annoys me:
```
    > bundle exec jekyll serve
Configuration file: /Users/***/_config.yml
            Source: /Users/***
       Destination: /Users/***/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
     Build Warning: Layout 'none' requested in assets/manifest.json does not exist.
     Build Warning: Layout 'none' requested in assets/scripts/sw.js does not exist.
                    done in 1.028 seconds.
```
'none' should be replaced with 'null' in these files

**Comment by ashmaroli** [comment]
@johannes-jansson `layout: none` is a declaration (available for `Jekyll::Page` objects from Jekyll 3.7) that is better than `layout: null`.
By setting `layout: null`, there is *a chance* that the value may get overridden when merging the page's `data` Hash with another Hash. But that is entirely avoided by using the `layout: none` front matter.

Another difference is that pages and documents with `layout: none` are not considered for placement into layouts at all during the site's rendering phase. With Jekyll 3.7 and above, you can see this using the `--verbose` switch:

### With `layout: null`
```
         Rendering: assets/manifest.json
  Pre-Render Hooks: assets/manifest.json
  Rendering Liquid: assets/manifest.json
  Rendering Markup: assets/manifest.json
  Rendering Layout: assets/manifest.json
```
### With `layout: none`
```
         Rendering: assets/manifest.json
  Pre-Render Hooks: assets/manifest.json
  Rendering Liquid: assets/manifest.json
  Rendering Markup: assets/manifest.json
```

---

Additionally, do note that `alembic-jekyll-theme-3.0.7` onward require at least Jekyll 3.8.0 which means you won't get the warning either ways if you were to update your gemset.

**Comment by daviddarnes** [comment]
@ashmaroli oh! Thanks for dropping in with this, does that mean I should change it back to `none`?

**Comment by daviddarnes** [comment]
I've updated Alembic to Jekyll 4.1 now so I'm hoping this is no longer an issue
