### ISSUE TITLE
Bundle warning about Ruby-SASS EOL

### ISSUE THREAD

**Issue by cutterbl** [daviddarnes/alembic#144]
Doing a fresh install, and noticed the following when running the `bundle install`

> Post-install message from sass:
> 
> Ruby Sass has reached end-of-life and should no longer be used.
> 
> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
>   primary implementation: https://sass-lang.com/install
> 
> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
>   sassc gem: https://github.com/sass/sassc-ruby#readme
> 
> * For more details, please refer to the Sass blog:
>   https://sass-lang.com/blog/posts/7828841

Not entirely sure what that means, in the context of this theme, but seems like maybe there are changes necessary?

**Comment by daviddarnes** [comment]
Hey @cutterbl, this is fine for now if you stick with the version of Jekyll you're running. It's fairly well explained here:
https://github.com/jekyll/jekyll-sass-converter/issues/74#issuecomment-516217160

It should get removed entirely when the theme is updated to work with Jekyll 4.0 and up, which you can follow along in #146. I'm going to close this issue. Thanks for notifying!
