### ISSUE TITLE
[Proposal] Please update for Jekyll 4.0

### ISSUE THREAD

**Issue by alex-oswald** [daviddarnes/alembic#146]
I get dependency issues when using Alembic with Jekyll 4.0.5.

```
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.0.0) x64-mingw32

    alembic-jekyll-theme x64-mingw32 was resolved to 1.5.3, which depends on
      jekyll (~> 3.3) x64-mingw32
```

Please relax the dependencies:
https://jekyllrb.com/news/releases/#upgrading-

**Comment by daviddarnes** [comment]
@oswaldtech I've yet to test this with the latest major version, feel free to create a pull request!

**Comment by cristianocasella** [comment]
Created a PR for this, it has a side feature that is not working anymore (css_inline), but it's covering my needs anyway. Any help there is appreciated.
