### ISSUE TITLE
[Proposal] Add charset tag to site header

### ISSUE THREAD

**Issue by johannes-jansson** [daviddarnes/alembic#151]
I recently resumed working on my jekyll site using this awesome theme, and ran into an issue with character encoding. There was no `<meta charset="utf-8">` present in my built site, so special characters "åäö" weren't displaying properly. 

I'm a novice to jekyll, but I fixed my issue by including this tag in `_includes/site-header.html`. I'd be happy to do a PR if this is a) the proper way to solve it and b) something that would be useful for other international users of the theme.

**Comment by daviddarnes** [comment]
Hey @johannes-jansson, thanks for the kind words! Have to say I'm kinda surprised this issue hasn't come up sooner 😅 . I think I encountered it very early on and ended up solving it with some sort of server configuration. Can I ask where you're hosting your site? If this is an issue on commonly used hosting platforms then maybe it should go in 🤔

**Comment by johannes-jansson** [comment]
For sure! But it turns out my fix only solved the issue for Firefox, not for Safari and Chrome. I'm hosting the site from an S3 bucket on AWS, using their automatic static site serving behind cloudfront. I ended up hotfixing it by manually setting charset on the individual files' meta-attributes on S3, but I'll need to find a better solution before next update. I'll get back to you once I have a solution that works on all modern browsers! And I'm eager to hear suggestions and willing to experiment :+1:

**Comment by daviddarnes** [comment]
It would be awesome if you find a full-proof solution, thanks!

> I ended up hotfixing it by manually setting charset on the individual files' meta-attributes on S3

I have a feeling that there's a way to set this for the whole server, and that's why the charset wasn't needed. Could be wrong though

**Comment by johannes-jansson** [comment]
Yeah, might just go for something like that. But I'm quite sure that I didn't have to do this for another Jekyll site that's hosted on an identical stack, where our annoying Swedish umlauts turned out just fine. I'll have a look this weekend and get back to you here!

**Comment by johannes-jansson** [comment]
Got around to it now. Writing `<meta charset="utf-8">` to `_includes/site-before-start.html` did seem to do the trick for all browsers, disregard my previous comment. I feel like utf-8 would be a reasonable default to be included in `_layouts/default.html`, but I'll leave that decision to you. My issue is solved in a clean manner and I'm happy 😊

Let me know if I should submit a PR including it in default.html!

PS. I should note that I haven't  set `lang` in `_config.yml`, that might be another way to solve this. I may try it in the future just to assuage my curiosity!

**Comment by daviddarnes** [comment]
@johannes-jansson Go for it! PRs welcome 😊 . Setting a lang shouldn't make a difference, but maybe? The default is `en-US` so your language may need to use alternate characters and ergo a different charset.

**Comment by johannes-jansson** [comment]
Yeah that's what I'm thinking. Sweet, will do! Thanks again for creating and maintaining this theme! :star:

**Comment by johannes-jansson** [comment]
Sorry for taking so long, PR is up now! Setting `lang` in `_config.yml` did not change anything, so I went ahead with the proposed solution.

**Comment by daviddarnes** [comment]
No problem, really appreciate the PR! I'll take a look and get this merged when I can 👍
