### ISSUE TITLE
[Question] setting colours in assets/styles.scss does not show an effect

### ISSUE THREAD

**Issue by Vidrax** [daviddarnes/alembic#157]
Hello,

I can't seem to get setting my own CSS colours to work. I did as you described and copied assets/styles.scss to my assets folder and edited it like this:

    ---
    title: false
    styles: true
    ---
    $accentColour: #6cb1bf;
    $headingColour: #00798d;
    $linkColour: #6cb1bf;
    $hoverColour: #00798d;
    @import "alembic";

These colour changes don't go through to the generated site, though. Am I missing something?

I tested the styles.scss file on a fresh jekyll directory to make sure that none of my other changes are at fault. Same result.

I am using jekyll 4.1.1 with Ruby 2.7.0p0 on Ubuntu 20.04, alembic theme 4.0.0 from gem install. I added Gemfile and Gemfile.lock as .txt attachments.

[Gemfile.txt](https://github.com/daviddarnes/alembic/files/5291763/Gemfile.txt)
[Gemfile.lock.txt](https://github.com/daviddarnes/alembic/files/5291765/Gemfile.lock.txt)

I would be very glad if you could have a look at this and help me find where I went wrong.

Many thanks for your theme, I like it a lot.

**Comment by Vidrax** [comment]
I found the solution myself: Under "Site performance settings", the documentation mentions that enabling inline CSS will switch off the parsing of assets/styles.scss. This is set by default in your example _config.yml, which I had copied and modified for my purposes. Setting css_inline to false let me use the styles.scss as I wanted.

**Comment by daviddarnes** [comment]
Pleased you found the solution @Vidrax, closing issue 🙂
