### ISSUE TITLE
Installation thoughts

### ISSUE THREAD

**Issue by budparr** [daviddarnes/alembic#18]
The process for installing via gem is a bit clunky (an upstream Jekyll problem, of course). I had better luck installing with Bundler (adding the alembic-jekyll-theme to my gem file). When running without, I got this error:
```jekyll 3.3.0 | Error:  The alembic-jekyll-theme theme could not be found.```

I wonder if, in addition to the set ups you have now (boilerplate, gem theme), you had a hybrid, where someone needs to download the entire Jekyll install (or clone a branch), run bundler, or something that updates the theme etc. That is to say, a download that has everything you need to run the gem-based theme. Hope that makes sense!

**Comment by daviddarnes** [comment]
This is great stuff @budparr, I understood you but only partially. I have to say I haven't done much testing for the gem. However using the steps stated it seemed to work fine. Could you run through what you did to get it working with a Gemfile?

I'd ideally like to stick with just a gem install method and a forking method, just to keep things simple

**Comment by budparr** [comment]
My process was to start with a jekyll new command, dump your demo folder in (overwriting what came in the folder), gem install your theme, then run jekyll serve. Using bundler, it was the same process, but I added your theme to my gemfile, ran `bundle update` and `bundle exec jekyll serve` and it ran fine.

So, my comment about the hybrid was meant to make the process easier by having one folder to download, not installing jekyll, then downloading a folder, then copying the folder over.

**Comment by daviddarnes** [comment]
I've opened a pull request that covers this if you want to take a look https://github.com/daviddarnes/alembic/pull/19

**Comment by daviddarnes** [comment]
Issue resolved in #19
