### ISSUE TITLE
[Question]: Blog list is having an issue

### ISSUE THREAD

**Issue by dwnatwick** [daviddarnes/alembic#180]
## Summary
I'm getting a couple of phantom posts on my post list.  Any idea where these might be coming from?

## Screenshots
![posts-issue](https://user-images.githubusercontent.com/39349581/156629271-c8e213e5-6370-4692-bfd9-a18f59b86dac.png)

**Comment by daviddarnes** [comment]
You’ve probably got some files floating around in your _posts folder

**Comment by daviddarnes** [comment]
Closing due to no reply

**Comment by dwnatwick** [comment]
Thank you @daviddarnes.  I actually ended up finding that I had 3 posts that had symbols in the title block that was conflicting with the yaml.  Thank you very much.
