### ISSUE TITLE
[Proposal]: Drop down sub-menus

### ISSUE THREAD

**Issue by multilingual-malaysian** [daviddarnes/alembic#182]
## Summary 
Would like to request for drop down sub-menus for the main ones in the navigation header. 

- title: "Contact Us"
    sublinks:
      - title: "Sub-menu of Contact Us"
        url: "#"
- title: "About"
   sublinks:
        - title: "Sub-menu of About"
           url: "#"

**Comment by daviddarnes** [comment]
A great idea, but not a simple one to add. I'll need to change how the template works and then introduce several front-end changes to account for dropdowns on large and small screens. I don't plan to add this in anytime soon so I'm going to close it, however you're welcome to submit a PR!
