### ISSUE TITLE
Easier way to understand something in _config.yml[Question]: Please add a title

### ISSUE THREAD

**Issue by manhcntt21** [daviddarnes/alembic#184]
## Summary

First, I run `bundle exec jekyll serve` and it work. 

Now i want to change something.

Example, I change titile in _config.yml file, tittle="something" 

![image](https://user-images.githubusercontent.com/27800932/193598580-123275c9-baf6-4aa8-9f1a-feff7c9deee6.png)

but my website have no change, even thought, I pressed F5

![image](https://user-images.githubusercontent.com/27800932/193599896-01cdde94-3081-4d10-954e-8cbe36da78da.png)

I found a way to do it, re-run application, I think it 's not good

ple, help me

**Comment by daviddarnes** [comment]
I'm afraid this is how Jekyll works, changing the config file in any Jekyll project means stopping the serve command and restarting it to see the change in the localhost site. This shouldn't be a problem if you're deploying it to some sort of deployment based hosting platform
