### ISSUE TITLE
[Question]: Change timezone

### ISSUE THREAD

**Issue by manhcntt21** [daviddarnes/alembic#185]
Hi, I want to change timezone, I found it in __config.yml. I changed Europe/London to Asia/Bangbok, but nothing change, time still Europe/Londo

![image](https://user-images.githubusercontent.com/27800932/199794636-9ec969eb-66aa-4623-b46c-2f925621d0b7.png)

How can i change the timezone? Thank you in advance!

**Comment by daviddarnes** [comment]
You might need to rebuild @manhcntt21, did you make sure to stop localhost and restart it again?

**Comment by manhcntt21** [comment]
yes, I stopped localhost and restarted it.

**Comment by daviddarnes** [comment]
How are you checking for the timezone?

**Comment by manhcntt21** [comment]
I change the time-zone, then I run it again, I edit the file and see it's still London time (on terminal), not Bangkok

**Comment by daviddarnes** [comment]
I don't think the timezone setting is the issue. Looks like you're setting a post for a whole day beforehand which means Jekyll will think it's in draft and won't build it. You should change the file to be todays date or a date in the past.

**Comment by daviddarnes** [comment]
Going to close this from lack of response

**Comment by manhcntt21** [comment]
Thank you, I'm sorry for the late reply!
