### ISSUE TITLE
[Bug]: Alembic cannot be installed in Jekyll 4?

### ISSUE THREAD

**Issue by urig** [daviddarnes/alembic#186]
## Summary

I tried installing Alembic in my blog that runs on Jekyll 4.0.1 and `bundle install` failed saying that it could not find compatible versions for gem "jekyll".

Is Alembic compatible with Jekyll 4? If not, what needs to be done to make it compatible? Perhaps I can get it done and submit a PR?

## To Reproduce
Steps to reproduce the behaviour:
1. Start a Jekyll devcontainer (I'm using the default used by VS Code 1.73.1, based on `mcr.microsoft.com/devcontainers/jekyll:0-bullseye`)
1. Run `bundle show jekyll` and verify you have `jekyll-4.0.1` installed.
2. Add the line `gem "alembic-jekyll-theme"` to your `Gemfile`.
3. Run `bundle install`.

## Expected behaviour
The `alembic-jekyll-theme` should be installed successfully

## Actual behaviour
`bundle` stops with an error that states:
> Bundler could not find compatible versions for gem "jekyll":
>  In Gemfile:
>    jekyll (~> 4.0.0)
> 
>   alembic-jekyll-theme was resolved to 1.5.3, which depends on
>      jekyll (~> 3.3)

## Screenshots
![image](https://user-images.githubusercontent.com/350687/203587793-d928bc09-90aa-4752-a5b6-8bdfeb9cd29b.png)

## Environment
- Ruby version: 2.7.6p219
- Jekyll version: 4.0.1
- Theme version: 1.5.3

**Comment by daviddarnes** [comment]
Looks like your versions are really far behind. The current version of Alembic is 4.1.0 https://rubygems.org/gems/alembic-jekyll-theme which requires Jekyll 4.1 to run https://github.com/daviddarnes/alembic/blob/18675fc841397c8a5bee01ddf9cfea257895ec58/alembic-jekyll-theme.gemspec#L18

Are you able to update any of your gem versions?
