### ISSUE TITLE
[Question]: add lightbox2 

### ISSUE THREAD

**Issue by emanuelegdepaoli** [daviddarnes/alembic#187]
I'am trying to add [lighbox2](https://github.com/lokesh/lightbox2) to my website created using alembic as theme. I followed the instructions in [this page](https://lokeshdhakar.com/projects/lightbox2/):

1- added the folders `css` and `js` with the required files.
2- added the folder `_layout` which includes a custom `default.html`, with the required modifications. 

However, when running the site locally, I get the following errors:
```
[2023-01-06 10:56:37] ERROR `/page/css/lightbox.css' not found. 
[2023-01-06 10:56:37] ERROR `/page/js/lightbox-plus-jquery.js' not found.
```

where `page ` is the website section where I try to load the images. That is, I have a `page.md` file in my main folder and my header in `_config.yml` is like the following:

```
# Header nav
navigation_header:
- title: Home
  url: /
- title: Mypage
  url: /page/
```

This is my first attempt to build a website and I really don't know how to solve the path problem.

**Comment by daviddarnes** [comment]
I think you need to place the CSS and JS files in the `assets` directory and make sure when you reference them you're pointing to them absolutely. From looking at the errors you posted you've either added `/page/` into the path, which isn't needed, or they are being set relatively which isn't right either. They need to be absolute so the files can be found from any page on the site. Hope this makes sense!

**Comment by emanuelegdepaoli** [comment]
Thank you for your help, the problem was that the CSS file, the JS file and the folder image have to be all in `assets` and I have to point to them absolutely.
