### ISSUE TITLE
[Question]: RSS feed link in footer not directing to /feed.xml

### ISSUE THREAD

**Issue by erindarrow** [daviddarnes/alembic#188]
## Summary
I'm trying to set up the RSS feed function for [my site](https://www.erindarrow.com) via repository https://github.com/erindarrow/erindarrow.github.io. 

Everything looks okay to me according to [this](https://github.com/jekyll/jekyll-feed) - 
I have gem 'jekyll-feed' in my Gemfile and 
`plugins: - jekyll-feed` in config.yml

Also in the [config.yml](https://github.com/erindarrow/erindarrow.github.io/blob/main/_config.yml) nav_footer, I have 
```
- title: RSS feed
  RSS: /feed.xml
```
which I thought would mean the RSS feed in the bottom nav link would point to: https://www.erindarrow.com/feed.xml but instead it points to the same page I am already on (www.erindarrow.com)

Thinking the RSS feed in config.yml was pointing to the wrong page, I also tried changing RSS: /feed.xml to RSS: /blog/feed.xml and that did not work either.

I must be doing something wrong here (maybe something simple) but I can't work out what it is. Can anyone help?

## Additional context
The actual feed general via the jekyll-feed plugin seems to work at: https://www.erindarrow.com/feed.xml - it seems to be the bottom nav link that doesn't direct to the feed correctly.

**Comment by daviddarnes** [comment]
Looks like a typo in your config code, it should be this:
```
- title: RSS feed
  url: /feed.xml
```
