### ISSUE TITLE
bundler could not find compatible version

### ISSUE THREAD

**Issue by kguion1** [daviddarnes/alembic#190]
## Summary
Hi! I am excited to start using this theme. I followed your instructions on using the theme and modified my Gemfile and _config file. However, when I run `bundle install` I am getting an error that it cannot find compatial version of jekyll-sitemap. I am not sure how to update this? Any help is appreicated!

## Screenshots
![image](https://github.com/daviddarnes/alembic/assets/42556019/0a085ee5-bcfb-43ae-ac09-27bbd917eb3c)

Here is my Gemfile
![image](https://github.com/daviddarnes/alembic/assets/42556019/6006dc8e-054b-4f29-ada8-c526aa8d1880)

jekyll 4.2.1
gem 3.1.2
ruby 2.7.0p0

## Additional context

Here is my repo: https://github.com/kguion1/kguion1.github.io/tree/main/docs

**Comment by daviddarnes** [comment]
Hey there! If you're wanting to use the theme with GitHub Pages I'd recommend forking the following repo and using the `remote-theme` branch as your main branch: https://github.com/daviddarnes/alembic-kit/tree/remote-theme

I've set this repo up to be starting points for people like yourself, and the `remote-theme` branch should be just enough to get you started with GitHub Pages. Hope this helps!

**Comment by kguion1** [comment]
Okay, thank you! When I fork it, I keep getting emails from github that say, "run failed: pages build and deployment"
Is there something I need to do after I fork it? I tried `bundle install` but I am still getting the same emial.

https://github.com/kguion1/kguion1.github.io

**Comment by daviddarnes** [comment]
Looks like you didn't use the `remote-theme` branch and used the main one instead. Try these steps:
1. Head to this link https://github.com/daviddarnes/alembic-kit/generate
2. In 'Repository name' add `kguion1.github.io`, and make sure you've deleted your old one
3. Check the box labelled 'Include all branches'
4. Click 'Create repository from template'
5. Go to the repo settings and change the default branch to `remote-theme`

Hopefully that should all work then. The alternative is to use [Netlify](https://www.netlify.com) which is completely free as well!

**Comment by kguion1** [comment]
Thank you for your patience and instructions! This was super helpful.
