### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/alembic#22]
Hi @YaManicKill, @case2111, @pizzapgh and @bawejakunal!

I noticed that you are all using Alembic in your own individual ways after I did a quick search on GitHub. This is awesome to see, so thank you all for using my theme 😄

I'd like to list a few example sites in the documentation to show what's possible with Alembic. I've listed the urls below, if you'd not like your site to be listed then let me know:

- http://katiesimonemusic.com/
- https://bawejakunal.github.io/
- http://case2111.github.io/
- http://www.10people.co.uk

**Comment by YaManicKill** [comment]
Hey, yeah, no problems with this. I'd probably prefer you would use my other blog, http://www.10people.co.uk, but that's perfectly fine. I also have a 3rd thing using your theme, http://alistair.mckinlay.me

Thanks for your theme, it's a great base. I'll probably be changing the look up a bit once I've had a think about how I want it to feel, but it fantastic to start with, and most themes I looked at had JS requirements (which is dreadful).

**Comment by daviddarnes** [comment]
@YaManicKill no problem, I've changed the link to your preferred site. That's great to hear! It's exactly the kind of thing I designed it for, a great starting point for people

**Comment by bawejakunal** [comment]
@daviddarnes sure you can list my site :)

**Comment by pizzapgh** [comment]
No problem. :)
