### ISSUE TITLE
Add a Code of Conduct and Contributing Guide

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/alembic#38]
People are going to need this if they want to contribute, so they know a bit more about what happens here. Just seen this project and it could be useful https://github.com/WeAllJS/weallbehave

Also https://github.com/WeAllJS/weallcontribute

**Comment by daviddarnes** [comment]
Added initial versions for now, they need work so they apply better to this project. I also noticed that @zkat is still working on these (sorry!), so I may have added these prematurely. I hope to get some time to return the favour and contribute back, regardless if I do or not Thank You! 💟

**Comment by zkat** [comment]
nah, knock yourself out. The whole point is that as they get improved, you'll be able to just bump your local version, run the script, and get any updates :)

**Comment by zkat** [comment]
Also: the CoC is a lot more solid and general-purpose than the contributing guide. I'll keep working on the latter until it's something more people can use. Patches always welcome! It's a work in progress, and it doesn't have to be just me. I'm really glad you find it useful ^_^ and kudos to @charlotteis who's helped a bunch with both docs.

**Comment by daviddarnes** [comment]
Thank you @charlotteis and @zkat! I'll be honest, this repo doesn't have a package.json 😓. Because it's a gem I haven't found a proper need for it, however this may be the right time to add it in. That way the documents match up with the type of project this is

**Comment by daviddarnes** [comment]
I guess these files will do the job for now, they probably need scanning over and revising but as a first cut I'm happy that they exist
