### ISSUE TITLE
hosting multiple github.io sites breaks navigation

### ISSUE THREAD

**Issue by zlskidmore** [daviddarnes/alembic#40]
Hi,

I noticed this theme is set up to work assuming a user/group has a single github.io domain. For example if the domain is:
https://name.github.io/repo/
instead of:
https://name.github.io/
things seem to break, navigation, posts, blog, image links, etc. Is there any way around this. I could change the navigation_header setting for example:
navigation_header:
  Home: /repo/
instead of 
Home: /

however this does not seem to work for "Search", also if running locally paths have to be reset or paths break again. I am new to jekyll, maybe I am missing something simple? Any help or advice you can give is appreciated, great theme!

**Comment by daviddarnes** [comment]
@zlskidmore hi there! Damn, I've been avoiding this bug because I thought that people could just add the nav urls themselves and it would be fine. I forgot that this wouldn't work for local installations.

I think I need to add `base_url` and make sure it's implemented correctly in the theme, see https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

I need to do some testing but I think if this is just added to the `_config.yml` it should propagate to all site relative links. Try this out and let me know, or even make a pull request if you like! 🌈

**Comment by daviddarnes** [comment]
I decided to come back to this issue to see what originally sparked your problem. Have to you tried just adding `https://name.github.io/repo` to the `url` option? Technically if your site is entirely there then your site url _would_ indeed be that yes?

**Comment by zlskidmore** [comment]
If you change the url to the full path things work if I recall correctly when hosting (after altering the navigation header). but any time you serve up your webpage locally you have to reset that url in the _config.yml. For example if:

`url: https://name.github.io/repo`

The site is served locally at localhost:4000 but live its at https://name.github.io/repo.

**Comment by daviddarnes** [comment]
Right, when I run the site locally I don't bother changing the `url` in the config and I just run `bundle exec jekyll serve --watch` and it builds and runs. The urls work, the nav works and everything else without breaking.

When it comes to pushing it live I just push it with the same url (and make sure my `CNAME` file contains the same record if I'm using a custom url) and it sill works ok.

I'm not sure whats happening between your local and remote versions?

**Comment by zlskidmore** [comment]
I think the problem is i'm hosting multiple sites on github.io so if this was my first site the path would be:
`https://name.github.io/`

but because it's my second site it automatically appends the repo name:
`https://name.github.io/repo`

and i'm forced to use that which causes the links to break, this issue should only appear if you have more than one site on github.io

**Comment by daviddarnes** [comment]
Do you have these repos public? I don't think it should be causing this kind of conflict

**Comment by zlskidmore** [comment]
heres the repo:
https://github.com/griffithlab/gen-viz-workshop

**Comment by zlskidmore** [comment]
my first attempt's before using the baseurl fix are around this commit:
9bb82849cdb583f64518f67805c673a1f13e6bab

so for example at that commit the url is at:
`https://name.github.io/repo/`

the about page is at:
`http://127.0.0.1:4000/about/`
but should be at:
`http://127.0.0.1:4000/gen-viz-workshop/about/`
because when hosting it's at:
`https://name.github.io/gen-viz-workshop/about/`

Basically the base url is not appended when hosting locally meaning you either have to change the url or navigation_header links.

**Comment by daviddarnes** [comment]
Ah I see now. Well really when you're working locally you don't _need_ to see the same url path on the live site.

For example:
`https://myname.github.io/myreponame` + `/mypage`

is the **same** as:
`http://localhost:4000` + `/mypage`

I think what's happening is that you're seeing `gen-viz-workshop/` on the live site and expecting it to be there in the local version, when in reality it doesn't need to be there

**Comment by daviddarnes** [comment]
@zlskidmore did you get this problem sorted? I'm going to close this issue, however I'm happy to continue with providing help 😃

**Comment by zlskidmore** [comment]
I think i've got it figured out, thanks for the help!
