### ISSUE TITLE
Aside does not follow scroll on Chrome

### ISSUE THREAD

**Issue by lassegs** [daviddarnes/alembic#54]
In Firefox, the aside sticks to the top of the viewport while scrolling down the page. This doesn't happen in Chrome, where the aside is stuck at top. See screenshots for illustration, first one is FF showing correct behavior, second is Chrome failing.

![screenshot from 2017-06-08 21-11-43](https://user-images.githubusercontent.com/10298672/26946312-1ceef274-4c8f-11e7-96f5-45a39798feca.png)
![screenshot from 2017-06-08 21-10-33](https://user-images.githubusercontent.com/10298672/26946311-1ceae314-4c8f-11e7-9405-5632ddcc533d.png)

**Comment by daviddarnes** [comment]
Hi there, and thanks for contributing! Which version of Chrome are you using? It should be working in Chrome 56 and up, could you check that all your browsers are up to date? The sidebar sections use `position: sticky` to stick them to the top of the screen, here's the current browser support http://caniuse.com/#feat=css-sticky

**Comment by lassegs** [comment]
Hey David, sorry about that. My Chrome repo got disabled in a dist upgrade, so I was running Chrome 54. Works fine updated to 59. Thanks for your great work.

**Comment by daviddarnes** [comment]
You're welcome!
