### ISSUE TITLE
Publication list with multiple columns

### ISSUE THREAD

**Issue by CorySimon** [daviddarnes/alembic#55]
Thanks, best Jekyll theme I've seen!

I desire to make a list of publications with two columns e.g.
http://yaghi.berkeley.edu/publications.html

How can I do so in this theme while allowing the width to scale automatically with different devices/browser settings? [And also work on Github pages.]

Thanks. Sorry if this is a newbie Jekyll question...

**Comment by daviddarnes** [comment]
Thanks for the praise Cory! I would advise asking this question on the [Jekyll forums](https://talk.jekyllrb.com/) as people will be able to give a more extended answer, also my theme works just like any other Jekyll site so the code won't differ much to anyone else.
