### ISSUE TITLE
Reducing font size

### ISSUE THREAD

**Issue by niahoo** [daviddarnes/alembic#58]
Hello, 

First, thanks a lot for what you've done, it's really helpful for a newcomer to jekyll ! Especially for typography and vertical rythm.

Now, I find that the maximum font size is too big (it's like 30px line height) : I want to show some code, and I think it requires too much scrolling for the reader.

I would like to use the second biggest font size. I figured out it has something to do with the breakpoint properties but I cannot find how you configure it.

Could you help me ? 

Thank you ;)

**Comment by daviddarnes** [comment]
@niahoo thank you very much for the kind words! Glad the typography works for you, it's one of the more difficult things to get 'just right' in web design.

Have you changed the font for your project? You might want to [set a new `cap-height`](https://github.com/daviddarnes/alembic/blob/master/_sass/_settings.scss#L17-L36) to match the custom font. Use this tool to find out the cap height of the font you're using https://codepen.io/sebdesign/pen/EKmbGL

If you want to just scale down all the typography, then you might want to [check out this comment](https://github.com/daviddarnes/alembic/issues/39#issuecomment-284039276).

**Comment by niahoo** [comment]
Ho I forgot to check the closed issues ! I can do what I want now :)



My font s
