### ISSUE TITLE
Search feature breaks with carriage returns

### ISSUE THREAD

**Issue by zlskidmore** [daviddarnes/alembic#61]
Hi,

I noticed that if one of your posts contains the text "\n" the search functionality breaks and is unable to find anything.

For example if I add the text \n (not an actual carriage return but the text) to 2016-08-27-example-post-one.md the search is not able to find anything.

I am guessing that when the search feature parses these pages it incorrectly interprets the "\n" as a new line instead of plain text and halts the search pre maturely. Not sure if this is true though or if it's easy to fix, though i'm happy to try.

**Comment by daviddarnes** [comment]
Thanks for spotting this! Looks like it's down to https://github.com/daviddarnes/alembic/blob/c829f3ecb470bd7245e043722dd97454c0d3bad2/assets/search.json#L15 and
https://github.com/daviddarnes/alembic/blob/master/assets/search.json#L25

I guess I need to find a way to strip new lines from the content but not the string `\n` 🤔

**Comment by daviddarnes** [comment]
Opened a PR to fix this @zlskidmore, let us know if you agree with this fix

**Comment by zlskidmore** [comment]
Thanks @daviddarnes, I think that works!
