### ISSUE TITLE
if post have a format markdown more than 60 characters at the first, the categories list layout will be block

### ISSUE THREAD

**Issue by wlon** [daviddarnes/alembic#65]
The root case is there is a logic truncatewords: 60 in the _includes/post-categories.html

{{ page.excerpt | markdownify |truncatewords: 60 }}   this statement will generate no closing tag html

**Comment by daviddarnes** [comment]
I had to read this a couple of times to understand it, but are you saying that if a post is shorter than 60 characters then no closing `</p>` will be generated? That's super annoying, but thanks for finding it!

**Comment by wlon** [comment]
https://github.com/wlon/blog/blob/master/_posts/2012-05-07-mac-os-x-terminal-shortcut-key.markdown

Here is my post markdown. you can have a test with it. but this post writed by Chinese, hope it will not impact your test.
