### ISSUE TITLE
List all post 

### ISSUE THREAD

**Issue by LauraLaureus** [daviddarnes/alembic#76]
Hi!
I'm new to jekyll and I'm using alembric. I would like to create a "Latest posts" listing the last n post. 
I tried using the following code https://gist.github.com/erjjones/1998382  replacing site.posts by site.collections.posts or collections.post in the index.md but nothing is displayed. 
Can you help me with this?

I have the example-post-one under _post folder so I expect this one to appear :|

**Comment by LauraLaureus** [comment]
Well I figure it out! 
I have to surround the original code with div tag and it works. 
Thanks for reading.

**Comment by daviddarnes** [comment]
@LauraLaureus howdy! Glad you got it sorted!
