### ISSUE TITLE
Request for a official dark theme version

### ISSUE THREAD

**Issue by didaquis** [daviddarnes/alembic#81]
Hi. I would like to know if there are plans to launch a dark version of theme?

**Comment by daviddarnes** [comment]
@didaquis hi there! I've not considered it before, but seems like a reasonable request. In the meatime you could overwrite the default `_sass/_settings.scss` file with your own colour settings. I've created a basic example:
``` scss
// new _sass/_settings.scss file

// Background colours
$backgroundColour:#1a1a1a;
$codeBackgroundColour:#323232;
$featureBackgroundColour:#000000;
$accentColour:#a5bdff;
$headingColour:#ffffff;
$bodyColour:#d2d2d2;
$linkColour:#5380ff;
$hoverColour:#a5bdff;
$focusColour:#fa407b;
$captionColour:#808080;
$white:#fff;

// Typography
$bodytype: (
  font-family: 'Georgia, serif',
  regular: 400,
  bold: 700,
  italic: italic,
  cap-height: 0.75
);

$headingtype: (
  font-family: '"Merriweather", serif',
  regular: 400,
  bold: 700,
  cap-height: 0.75
);

$monospacetype: (
  font-family: 'Menlo, monospace',
  regular: 400,
  cap-height: 0.68
);

// Font import, if you're using a non-standard web font
@import url('https://fonts.googleapis.com/css?family=Merriweather:400,700');
```
Which produces this:
<img width="1280" alt="screen shot 2018-02-10 at 15 53 43" src="https://user-images.githubusercontent.com/1177460/36063922-2328dd9a-0e7b-11e8-947b-66b943f23e40.png">

The only issue you may hit is that the default code highlighting colour isn't readable against dark backgrounds. So I'd recommend picking a dark code colour theme from pygments css http://richleland.github.io/pygments-css/ and replacing the `_sass/_syntax.css` file. fruity.css looks good.

Hope you find this useful!

**Comment by didaquis** [comment]
Thank you!
