### ISSUE TITLE
[Bug] Header image doesn't show up in second page of blog posts

### ISSUE THREAD

**Issue by SimonEnsemble** [daviddarnes/alembic#93]
Please see my Blog based on the alembic theme [here](https://simonensemble.github.io/blog/). When you go to the second page of the blog posts, the header image disappears. How can I keep it from disappearing? Thanks.

**Comment by daviddarnes** [comment]
Hi @SimonEnsemble, I think it's because you're using a relative path for your feature email https://github.com/SimonEnsemble/SimonEnsemble.github.io/blob/master/_config.yml#L63

Better to use an absolute path:
```
feature_image: "https://simonensemble.github.io/images/OregonCoast.JPG"
```

Hope this helps!
