### ISSUE TITLE
How to list more than two blog posts?

### ISSUE THREAD

**Issue by SimonEnsemble** [daviddarnes/alembic#98]
How can I control the number of blog posts displayed on the `Blog` tab? I cannot find any settings in `_config.yml` or `_includes/post-pagination.html`. I feel that displaying two per page is too little ([mine](https://simonensemble.github.io/blog/) displays two).

Thank you.

**Comment by daviddarnes** [comment]
@SimonEnsemble you want to check the `paginate` option, here's the line in the `_config.yml` file https://github.com/daviddarnes/alembic/blob/master/_config.yml#L35
